### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by cavi21** [davidlaprade/netsuite_elixir#6]
Hi @davidlaprade I was wondering if this project is still with intentions to progress or if you decided to leave it and use another solution to connect with Netsuite on an elixir app? in that case can you share your experience?

Thanks a lot!

**Comment by davidlaprade** [comment]
Hi @cavi21, thanks for reaching out. I'm not actively working on the project at the moment. If I remember correctly, this is where things stalled: https://github.com/r-icarus/detergentex/issues/9

I didn't end up finding another solution 😞

**Comment by cavi21** [comment]
Hi @davidlaprade thanks for the followup! At this point I think that maybe a "middleware" written in another language that has better support for Netsuite is the way to go, adds complexity and another step, but at least there are more mature libraries out there for this.

Again thanks for the reply!
